API_KEY : "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"
PROXY : 'http://127.0.0.1:7000'
MAX_CHAT_HISTORY : "1000"

MIN_CATEGORY_SIM : "0.7"
TOY_INFO_PATH : ['shopping_assistant/toy_info.json',
                 'shopping_assistant/bb_info.json']